package de.dhbw.ravensburg.zuul.room;
/**
 * Enumeration of all room types.
 * 
 * @author Frederick Dammeier - Philipp Schneider
 */
public enum RoomType {
	EMPTY_ROOM, FOREST_VERTICAL, FOREST_HORIZONTAL, FOREST_NORTH, RUIN, RUIN_LABORATORY, RUIN_DUNGEON, RUIN_MAGE, RUIN_LIBRARY, RUIN_TOP, RUIN_BASEMENT, BEACH_WEST, BEACH_EAST, BEACH_NORTH, BEACH_SOUTH, FINISH, REDWOOD, FOREST_SOUTHWEST, FOREST_NORTHWESTSOUTH, FOREST_SOUTHWEST2, RUIN_ENTRANCE_WEST, RUIN_ENTRANCE_EAST, RUIN_ENTRANCE_NORTH, RUIN_ENTRANCE_SOUTH, RUIN_STAIRCASE_1;
}
