package de.dhbw.ravensburg.zuul.room;

public enum RoomType {
	EMPTY_ROOM, FOREST_VERTICAL, FOREST_HORIZONTAL, FOREST_NORTH, RUIN, RUIN_LABORATORY, RUIN_DUNGEON, RUIN_MAGE, RUIN_LIBRARY, RUIN_TOP, RUIN_BASEMENT, BEACH_WEST, BEACH_EAST, BEACH_NORTH, BEACH_SOUTH, FINISH, REDWOOD;
}
